name: Test AWS OIDC

on:
  workflow_dispatch: # 手動実行

permissions:
  id-token: write   # ← OIDCで必須
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::628203515429:role/GitHubActions-ResearchForm-Role
          aws-region: ap-northeast-1

      - name: Who am I?
        run: aws sts get-caller-identity